alias c="clear"
alias sudo="sudo "
alias att="tmux attach -t"
alias p2="python2"
alias p3="python3"
alias sp2="source ~/envs/py2_garden/bin/activate"
alias sp3="source ~/envs/py3_garden/bin/activate"
